# Air configuration for hot reload on Windows
# This file tells Air how to watch for changes and rebuild your Go application

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Binary name and location
  bin = "./tmp/main.exe"
  
  # Command to run to build your project
  cmd = "go build -o ./tmp/main.exe ./cmd/server"
  
  # Watch these file extensions
  include_ext = ["go", "tpl", "tmpl", "html"]
  
  # Ignore these directories
  exclude_dir = ["uploads", "tmp", "vendor", "testdata", "migrations"]
  
  # Watch these directories
  include_dir = ["cmd", "internal", "pkg"]
  
  # Exclude files matching these patterns
  exclude_file = []
  
  # Exclude unchanged files
  exclude_unchanged = true
  
  # Follow symlinks
  follow_symlink = true
  
  # Build delay after change detected (milliseconds)
  delay = 1000
  
  # Stop previous build before starting new one
  stop_on_error = true
  
  # Send interrupt signal before killing process
  send_interrupt = true
  
  # Delay after sending interrupt signal (milliseconds)
  kill_delay = 500

[build.windows]
  # Windows specific settings
  cmd = "go build -o ./tmp/main.exe ./cmd/server"

[log]
  # Show log timestamps
  time = true

[color]
  # Colorize logs
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
  app = ""

[misc]
  # Clean tmp directory on start
  clean_on_exit = true